version: '3'

services:
  web:
    build: ./web
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/web_django
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    image: postgres:14.2
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'post'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '12345678'
    restart: always

